# Generated by Django 5.0.4 on 2024-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games_app', '0002_rename_high_score_playergamelink_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
