# Generated by Django 5.0.4 on 2024-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('games_app', '0003_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamelink',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
